version: 3

services:
    database:
        image: postgres:18-alpine
        env_file:
            - .env
        volumes:
            - database-data:/var/lib/postgresql
        ports:
            - 127.0.0.1:5432:5432
        networks:
            - kfc-net

    app:
        build:
            dockerfile: Containerfile
            context: .
        image: registry.jirik.dev/kfc/app:latest
        env_file:
            - .env
        ports:
            - 3000:3000
        networks:
            - kfc-net

    prisma:
        build:
            dockerfile: container-prisma/Containerfile
            context: .
        image: registry.jirik.dev/kfc/prisma:latest
        env_file:
            - .env
        ports:
            - 5555:5555
        networks:
            - kfc-net
        command: yarn exec prisma studio

networks:
    kfc-net:

volumes:
    database-data:
