version: 3


services:

  database:
    image: postgres:16-alpine
    env_file:
      - .env.compose
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - kfc-net

  app:
    build:
      dockerfile: Containerfile
      context: .
    env_file:
      - .env.compose
    ports:
      - 3000:3000
    networks:
        - kfc-net

networks:
  kfc-net: 


volumes:
  database-data:
