version: 3


services:

  database:
    image: postgres:16-alpine
    environment:
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - kfc-net


networks:
  kfc-net: 


volumes:
  database-data:
