FROM node:22-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY .yarnrc.yml ./
COPY .yarn ./.yarn
COPY container-prisma/package.json ./
COPY container-prisma/yarn.lock ./
COPY prisma ./prisma

RUN yarn --immutable
